### ISSUE TITLE
[Feature Request] Expose `buildThemeObject` when using `ReactThemeStudioTemplateRenderer`

### ISSUE THREAD

**Issue by SwaySway** [aws-amplify/amplify-codegen-ui#338]
I'd like the ability to codegen the shape of the object so it's easy to pass into createTheme in memory.
The following function returns the shape already though it's private
https://github.com/aws-amplify/amplify-codegen-ui/blob/8e459b43520d679a407db07e7278af1492d69b4e/packages/codegen-ui-react/lib/react-theme-studio-template-renderer.ts#L119-L131

**Comment by dpilch** [comment]
This function returns the TypeScript AST of the object. I'm assuming you want the JSON object itself?

**Comment by SwaySway** [comment]
> This function returns the TypeScript AST of the object. I'm assuming you want the JSON object itself?

Yea it might end up being a different function but yea it would the JSON object.

**Comment by alharris-at** [comment]
New API has been pushed, and is available in the `q1-release` tagged version on NPM. Resolving.
